# Generated by Django 5.1.5 on 2025-02-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_cd', models.CharField(max_length=20, unique=True)),
                ('movie_nm', models.CharField(max_length=255)),
                ('open_dt', models.DateField()),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('box_office_sales', models.BigIntegerField(blank=True, null=True)),
                ('box_office_rank', models.IntegerField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
