# Generated by Django 5.1.5 on 2025-02-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='overview',
        ),
        migrations.AlterField(
            model_name='movie',
            name='box_office_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='open_dt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
