# Generated by Django 5.1.5 on 2025-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_movie_actors_remove_movie_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='audi_acc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='audi_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
