# Generated by Django 5.1.5 on 2025-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_movie_audi_acc_movie_audi_cnt_movie_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('vote_average', models.FloatField()),
                ('popularity', models.FloatField()),
            ],
        ),
    ]
